### PR TITLE
support null value in where and prop

### PR DESCRIPTION
**Pull request by khoale88**

### CODE REVIEW

**Comment by j6k4m8** [comment]
This is so awesome, thank you for the contribution @khoale88! Would you be willing to write a unit-test or two to verify that this is working before merging? If not, I can add a few tomorrow or Monday and then I will merge it in ASAP. 

I'm super grateful for your work here!! Thanks for making Grand-Cypher even better :)

**Comment by khoale88** [comment]
> This is so awesome, thank you for the contribution @khoale88! Would you be willing to write a unit-test or two to verify that this is working before merging? If not, I can add a few tomorrow or Monday and then I will merge it in ASAP.
> 
> I'm super grateful for your work here!! Thanks for making Grand-Cypher even better :)

Thank you. Will do it tmr.

**Comment by khoale88** [comment]
Hi @j6k4m8 , I have updated the PR with 2 tests, one for note attribute, one for where. Can you check?
Anw, thank you for the great repo.

**Comment by j6k4m8** [comment]
Looks good @khoale88 !!! Thanks again, really excited this repository has been useful to you! Everything looks ready to me, is this okay with you to merge?

**Pull request merged**
