### PR TITLE
Add path groups

### PR DESCRIPTION
**Pull request by davidmezzetti**
Initial implementation of #26 as discussed in #35. 

After thinking about how a standard node and relationship are returned, this initial implementation mirrors that for paths.

For example:

```cypher
MATCH (A)-[R]->(B)
RETURN A, R, B
```

Returns:

```
(A node id, R relationship attributes, B node id)
```

With this change:

```cypher
MATCH P = (A)-[R]->(B)
RETURN P
```

Returns:

[node id1, {relationship attributes} node id2]

The plumbing is now in place to return the data in whatever format we think makes sense. 

I think I modified the lark spec to make the path_clause optional. The tests pass.

### CODE REVIEW

**Comment by j6k4m8** [comment]
This is awesome!! Ready to merge?

**Comment by davidmezzetti** [comment]
Ready from my end.

I was hoping to get this into a new grandcypher release and require that version or greater when using it with txtai. 

This feature is going to enable this functionality: https://github.com/neuml/txtai/issues/540

**Comment by j6k4m8** [comment]
Groovy — will merge now!

**Comment by davidmezzetti** [comment]
Sure. I can push another commit with a change log update for 0.6.0. I'll also update setup.py.

**Comment by davidmezzetti** [comment]
Just pushed the updated CHANGELOG and bumped version in setup.py

**Review by j6k4m8 — APPROVED** [review]

**Pull request merged**
